Recover buffer position after reset
jlab-sensing/ENTS-node-firmware pull request #142
Opened 2024-10-28 21:49 UTC by mirellameelo

**Name/Affiliation/Title**
Ella Ferraz/UCSC

**Purpose of the PR**
Refer to issue #69 

**Development Environment**
Ubuntu 20.04.6 LTS
PlatformIO Core, version 6.1.16
Hardware: 2.2.1

**Test Procedure**
To verify the functionality of data retrieval from FRAM after power outages, follow these steps:

1. Run `example_retrieve_data`

- Upload and run `example_retrieve_data` on the STM32 board. This will initialize the system and write sample data to the FRAM buffer.

2. Simulate Power Outage

- After the initial setup, manually remove power from the STM32 board to simulate an unexpected power outage.
- Reconnect power to restart the board.
- **Alternatively:**

    Press the Restart button on the STM32 board to simulate a power cycle without physically disconnecting power.

Expected Behavior on Reboot

- Upon reboot, the program should retrieve the saved `read_addr`, `write_addr`, and `buffer_len` states from FRAM.
- Pressing the **Restart** button should add additional test data to the FRAM buffer, confirming that data integrity and buffer states are preserved across power cycles.

3. Unit Test

- The `test_LoadSaveBufferState` function verifies that `read_addr` and `write_addr` in FRAM accurately reflect buffer states before and after simulated power outages.

- This unit test ensures that the buffer state is correctly saved and reloaded, maintaining data continuity across restarts.

**Additional Context**
The unit test for this feature validates the implemented methods at a software level when the "Restart" button is clicked. It ensures that the buffer state (read_addr and write_addr) accurately reflects data continuity across simulated restarts.

For a full testing procedure, including power cycle simulation, please refer to the Test Procedure section.

**Task List**

- [ ] Update `CHANGELOG.md`
- [ ] Static code analysis passes
- [ ] All environments can be built
- [ ] All tests pass
- [ ] Clear documentation for new code
- [ ] Linting passes
- [ ] (If applicable) Version bump python library

**Relevant Issues**
Closes #69

2024-11-01 01:56 UTC, jmadden173 requested changes
Main comments are:
- removing print statements from the library (use `APP_LOG` or `APP_PRINTF`) in the future
- Convert load/save functions to use globally defined address variables
- Adding test for the save method

2024-11-01 01:56 UTC, jmadden173 commented on stm32/lib/fram/src/fifo.c
> +void print(const char *format, ...) {
Remove this function, use `APP_PRINTF` or `APP_LOG` instead

2024-11-01 01:56 UTC, jmadden173 commented on stm32/lib/fram/src/fifo.c
> +  FramStatus status;
Initialize a value

2024-11-01 01:56 UTC, jmadden173 commented on stm32/lib/fram/src/fifo.c
> +  return FRAM_OK;
Return status and initialize on creation

2024-11-01 01:56 UTC, jmadden173 commented on stm32/test/test_fifo/test_fifo.c
Don't see a test for saving the buffer state. The test doesn't call the load. When you add a test for it you can put it before the load buffer state and test them in sequence. IE the first test saves data, the second clears the buffer, restores it, and checks that the data is still available.

2024-11-01 01:56 UTC, jmadden173 commented on stm32/lib/fram/include/fifo.h
The addresses for read, write, and len are defined "privately" in the fifo library while the buffer save/load functions require the addresses to be passed as parameters. The functions can reference the globally defined variables.

2024-11-01 01:56 UTC, jmadden173 commented on stm32/lib/fram/src/fifo.c
As a general practice don't print anything within libraries as it clutters the log of the LoRa firmware. The FramStatus codes give us a way to print out debug messages from the main code.

2024-12-06 23:52 UTC, mirellameelo commented on stm32/test/test_fifo/test_fifo.c
FramPut calls  FramSaveBufferState(). I'll add a comment.

2024-12-13 14:38 UTC, jmadden173 commented
Try merging upstream changes from `release/2.2.0` and it should fix the build errors.

2024-12-20 23:42 UTC, jmadden173 approved these changes
lgtm

2024-12-21 00:56 UTC, merged